"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "../../lib/supabase";

type Analysis = { purpose:string; targetUsers:string; coreProblem:string; positioning:string; keyFeatures:string[]; businessModel:string; improvements:string[]; mvpFeatures:string[]; summary:string };
type DesignDirection = { palette:string; typography:string; layoutStyle:string; visualTone:string };
type Concept = { productName:string; productDescription:string; features:string[]; navigation:string[]; pages:{name:string;purpose:string;sections:string[]}[]; designDirection:DesignDirection };
type Project = { id:string; name:string; website_url:string; product_description:string; target_customer:string; analysis:Analysis|null; concept:Concept|null; conversation:{role:"user"|"assistant";content:string}[]; updated_at:string };
const empty = { name:"", website_url:"", product_description:"", target_customer:"" };

export default function Home() {
  const [session, setSession] = useState<Session|null>(null), [mode, setMode] = useState<"login"|"signup">("signup");
  const [projects, setProjects] = useState<Project[]>([]), [project, setProject] = useState<Project|null>(null), [form, setForm] = useState(empty);
  const selectedProjectRef = useRef<Project|null>(null);
  const [busy, setBusy] = useState(""), [error, setError] = useState(""), [instruction, setInstruction] = useState(""), [buildDiagnostics, setBuildDiagnostics] = useState<string[]>([]);
  function traceBuild(message:string) { console.info(`[Build My Product] ${message}`); setBuildDiagnostics((current) => [...current, message]); }
  useEffect(() => { supabase.auth.getSession().then(({data}) => setSession(data.session)); const {data:l}=supabase.auth.onAuthStateChange((_,s)=>setSession(s)); return()=>l.subscription.unsubscribe(); },[]);
  useEffect(() => { if(session) { void supabase.from("projects").select("*").order("updated_at",{ascending:false}).then(({data,error}) => { if(error) { console.error("Supabase project load failed:", error); setError(error.message); } else { const loaded=data as Project[]||[];setProjects(loaded);const firstProject=loaded[0];if(!selectedProjectRef.current&&firstProject) {selectedProjectRef.current=firstProject;setProject(firstProject);setForm({name:firstProject.name,website_url:firstProject.website_url,product_description:firstProject.product_description,target_customer:firstProject.target_customer});setError("");} } }); } },[session]);
  function selectProject(next:Project|null) {selectedProjectRef.current=next;setProject(next)}
  function open(p:Project) {selectProject(p);setForm({name:p.name,website_url:p.website_url,product_description:p.product_description,target_customer:p.target_customer});setError("")}
  function reset() {selectProject(null);setForm(empty);setError("")}
  async function save() {
    if(!form.name||!form.product_description||!form.target_customer) return setError("Project name, product description, and target customer are required.");
    if(!session) return setError("Your session expired. Please sign in again.");
    setBusy("save");setError(""); const record={...form,user_id:session.user.id,analysis:project?.analysis||null,concept:project?.concept||null,conversation:project?.conversation||[]};
    const result=project?await supabase.from("projects").update(record).eq("id",project.id).select().single():await supabase.from("projects").insert(record).select().single(); setBusy("");
    if(result.error) { console.error("Supabase project save failed:", result.error); return setError(result.error.message); } const p=result.data as Project;selectProject(p);setProjects(x=>[p,...x.filter(y=>y.id!==p.id)]);
  }
  async function api(path:string,body:object,trace?: (message:string)=>void) {const {data:{session:activeSession}}=await supabase.auth.getSession();if(!activeSession)throw new Error("Your session expired. Please sign in again.");trace?.(`Calling ${path}.`);const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${activeSession.access_token}`},body:JSON.stringify(body)});trace?.(`${path} returned HTTP ${r.status}.`);const raw=await r.text();console.info(`[Build My Product] Raw ${path} response:`,raw);trace?.(`Raw ${path} response: ${raw}`);let d;try {d=JSON.parse(raw);trace?.("Response JSON parsing succeeded.");} catch(parseError) {console.error("[Build My Product] Response JSON parsing failed:",parseError);trace?.("Response JSON parsing failed.");throw new Error(`Could not parse the server response: ${parseError instanceof Error?parseError.message:"Unknown parsing error"}`);}if(!r.ok)throw new Error(d.error||"Request failed.");return d}
  async function persist(p:Project) {const {data,error}=await supabase.from("projects").update({...form,analysis:p.analysis,concept:p.concept,conversation:p.conversation}).eq("id",p.id).select().single();if(error) { console.error("Supabase project persistence failed:", error); throw new Error(error.message); } const saved=data as Project;setProjects(x=>[saved,...x.filter(y=>y.id!==saved.id)]);return saved}
  async function analyze() {if(!project){await save();return}setBusy("analyze");setError("");try{const {analysis}=await api("/api/analyze",form);const p={...project,analysis};const saved=await persist(p);selectProject(saved)}catch(e){setError(e instanceof Error?e.message:"Analysis failed.")}finally{setBusy("")}}
  async function build() {setBuildDiagnostics([]);traceBuild("Build button clicked.");if(!project?.analysis) {const message="Run an analysis before building.";traceBuild(message);return setError(message);}setBusy("build");setError("");try{traceBuild("Preparing the /api/build request.");const {concept}=await api("/api/build",{...form,analysis:project.analysis},traceBuild);if(!concept)throw new Error("The build response was successful but did not include a concept.");traceBuild("Build response includes a concept.");const p={...project,concept,conversation:[{role:"assistant" as const,content:"Your initial concept is ready. Tell me what you would like to change."}]};const saved=await persist(p);traceBuild("Concept response saved to Supabase.");selectProject(saved);traceBuild("Project state updated with the saved concept.");}catch(e){const message=e instanceof Error?e.message:"Build failed.";console.error("[Build My Product] Build flow failed:",e);traceBuild(`Build failed: ${message}`);setError(message)}finally{setBusy("")}}
  async function refine(e:FormEvent) {e.preventDefault();if(!project?.concept||!instruction.trim())return;const message=instruction.trim();setInstruction("");setBusy("refine");try{const {concept,reply}=await api("/api/refine",{concept:project.concept,instruction:message,context:form});const p={...project,concept,conversation:[...project.conversation,{role:"user" as const,content:message},{role:"assistant" as const,content:reply}]};const saved=await persist(p);selectProject(saved)}catch(e){setError(e instanceof Error?e.message:"Update failed.")}finally{setBusy("")}}
  async function authenticate(e:FormEvent<HTMLFormElement>) {e.preventDefault();setBusy("auth");setError("");const d=new FormData(e.currentTarget),email=String(d.get("email")),password=String(d.get("password"));const r=mode==="signup"?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});setBusy("");if(r.error)setError(r.error.message);else if(mode==="signup"&&!r.data.session)setError("Check your inbox to confirm your account, then sign in.")}
  if(!session)return <><Landing start={()=>document.getElementById("auth")?.scrollIntoView({behavior:"smooth"})}/><section className="auth-section" id="auth"><form className="auth-card" onSubmit={authenticate}><p className="eyebrow">Get started</p><h2>{mode==="signup"?"Build your next product":"Welcome back"}</h2><label>Email<input name="email" type="email" required placeholder="you@company.com"/></label><label>Password<input name="password" type="password" minLength={6} required placeholder="At least 6 characters"/></label>{error&&<p className="notice">{error}</p>}<button disabled={!!busy}>{busy?"Working...":mode==="signup"?"Create account":"Sign in"}</button><button type="button" className="text-button" onClick={()=>setMode(mode==="signup"?"login":"signup")}>{mode==="signup"?"Already have an account? Sign in":"Need an account? Create one"}</button></form></section></>;
  return <main className="workspace"><aside><Link className="brand" href="/">forge<span>AI</span></Link><button className="new-project" onClick={reset}>+ New project</button><p className="side-label">Your projects</p><nav>{projects.map(p=><button key={p.id} className={p.id===project?.id?"project active":"project"} onClick={()=>open(p)}><strong>{p.name}</strong><small>{new Date(p.updated_at).toLocaleDateString()}</small></button>)}</nav><button className="logout" onClick={()=>supabase.auth.signOut()}>Sign out</button></aside><section className="work-area"><header><div><p className="eyebrow">Product workspace</p><h1>{project?.name||"New product"}</h1></div><button onClick={save} disabled={!!busy}>{busy==="save"?"Saving...":"Save project"}</button></header>{error&&<p className="error">{error}</p>}{buildDiagnostics.length>0&&<pre className="error">{buildDiagnostics.join("\n")}</pre>}<div className="workspace-grid"><section className="intake panel"><h2>Product brief</h2><p>Give Forge enough context to make an informed recommendation.</p><Field label="Project name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Compass CRM"/></Field><Field label="Website URL (optional)"><input type="url" value={form.website_url} onChange={e=>setForm({...form,website_url:e.target.value})} placeholder="https://example.com"/></Field><Field label="What are you building?"><textarea value={form.product_description} onChange={e=>setForm({...form,product_description:e.target.value})} placeholder="Describe the product and customer need."/></Field><Field label="Target customer"><textarea value={form.target_customer} onChange={e=>setForm({...form,target_customer:e.target.value})} placeholder="Who needs it, and in what context?"/></Field><div className="actions"><button className="secondary" onClick={save} disabled={!!busy}>Save</button><button onClick={analyze} disabled={!!busy}>{busy==="analyze"?"Analyzing...":"Analyze product"}</button></div></section><section className="results">{project?.analysis?<AnalysisView analysis={project.analysis} build={build} busy={busy==="build"}/>:<Empty title="Your analysis will appear here" text="Save this project and run an analysis to get a clear product strategy."/>}{project?.concept&&<ConceptView concept={project.concept} conversation={project.conversation} instruction={instruction} setInstruction={setInstruction} submit={refine} busy={busy==="refine"}/>}</section></div></section></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}) {return <label>{label}{children}</label>}
function AnalysisView({analysis,build,busy}:{analysis:Analysis;build:()=>void;busy:boolean}) {return <section className="panel analysis"><div className="panel-top"><div><p className="eyebrow">AI analysis</p><h2>Product opportunity</h2></div><button onClick={build} disabled={busy}>{busy?"Building...":"Build my product"}</button></div><p className="summary">{analysis.summary}</p><div className="analysis-grid"><Fact l="Purpose" v={analysis.purpose}/><Fact l="Target users" v={analysis.targetUsers}/><Fact l="Core problem" v={analysis.coreProblem}/><Fact l="Positioning" v={analysis.positioning}/><Fact l="Business model" v={analysis.businessModel}/></div><List label="Key features" items={analysis.keyFeatures}/><List label="Suggested improvements" items={analysis.improvements}/><List label="Proposed MVP" items={analysis.mvpFeatures}/></section>}
function ConceptView({concept,conversation,instruction,setInstruction,submit,busy}:{concept:Concept;conversation:{role:string;content:string}[];instruction:string;setInstruction:(v:string)=>void;submit:(e:FormEvent)=>void;busy:boolean}) {console.info("[Build My Product] ConceptView received concept:",concept);return <section className="panel concept"><p className="eyebrow">Product concept</p><p className="notice">Debug: ConceptView received the generated concept.</p><h2>{concept.productName}</h2><p className="summary">{concept.productDescription}</p><div className="direction"><b>Design direction</b><dl><div><dt>Palette</dt><dd>{concept.designDirection.palette}</dd></div><div><dt>Typography</dt><dd>{concept.designDirection.typography}</dd></div><div><dt>Layout style</dt><dd>{concept.designDirection.layoutStyle}</dd></div><div><dt>Visual tone</dt><dd>{concept.designDirection.visualTone}</dd></div></dl></div><div className="concept-columns"><List label="Core features" items={concept.features}/><List label="Navigation" items={concept.navigation}/></div><div className="page-map"><h3>Page structure</h3>{concept.pages.map(p=><article key={p.name}><strong>{p.name}</strong><span>{p.purpose}</span><small>{p.sections.join(" · ")}</small></article>)}</div><div className="conversation">{conversation.map((m,i)=><p className={m.role} key={i}>{m.content}</p>)}</div><form className="refine" onSubmit={submit}><input value={instruction} onChange={e=>setInstruction(e.target.value)} disabled={busy} placeholder="Make the design more premium..."/><button disabled={busy||!instruction.trim()}>{busy?"Updating...":"Update"}</button></form></section>}
function Fact({l,v}:{l:string;v:string}) {return <div className="fact"><b>{l}</b><p>{v}</p></div>}
function List({label,items}:{label:string;items:string[]}) {return <div className="list"><h3>{label}</h3><ul>{items.map((v,i)=><li key={i}>{v}</li>)}</ul></div>}
function Empty({title,text}:{title:string;text:string}) {return <section className="empty"><div>✦</div><h2>{title}</h2><p>{text}</p></section>}
function Landing({start}:{start:()=>void}) {return <main className="landing"><nav className="landing-nav"><Link className="brand" href="/">forge<span>AI</span></Link><button className="link-button" onClick={start}>Sign in</button><button onClick={start}>Start building</button></nav><section className="hero"><p className="eyebrow">Product thinking, amplified</p><h1>Turn a rough idea into a product people want.</h1><p>Forge analyzes your market context, frames the opportunity, and gives you an editable product blueprint in minutes.</p><button onClick={start}>Build with Forge <span>→</span></button><div className="hero-demo"><div>Product opportunity <i></i><i></i><i></i></div><section><article><small>POSITIONING</small><strong>The focused operating system for independent studios.</strong><p>Connect project decisions to the work that happens next.</p></article><ul><li>01 Client workspace</li><li>02 Project command center</li><li>03 Decision history</li></ul></section></div></section><section className="trust"><span>Built for clear thinkers at</span><b>STARTUPS</b><b>STUDIOS</b><b>VENTURES</b><b>PRODUCT TEAMS</b></section><section className="features"><div><p className="eyebrow">A faster first draft</p><h2>Everything you need to shape the work before you build it.</h2></div><div className="feature-grid"><article><b>01</b><h3>Read the landscape</h3><p>Bring your existing site and idea together in one grounded analysis.</p></article><article><b>02</b><h3>Find the sharp edge</h3><p>Clarify customers, positioning, MVP scope, and overlooked opportunities.</p></article><article><b>03</b><h3>Keep iterating</h3><p>Direct the concept in plain language as your point of view evolves.</p></article></div></section><section className="how"><p className="eyebrow">How it works</p><div><h2>From context to a confident starting point.</h2><ol><li><span>1</span>Add your product context</li><li><span>2</span>Review a strategic analysis</li><li><span>3</span>Refine a build-ready concept</li></ol></div></section><section className="pricing"><p className="eyebrow">Simple pricing</p><h2>Start with your next idea.</h2><article><span>Explorer</span><strong>$19 <small>/ month</small></strong><p>For individuals shaping products with intention.</p><button onClick={start}>Start building</button></article></section><footer><Link className="brand" href="/">forge<span>AI</span></Link><span>Product clarity for the curious.</span><span>© 2026 Forge AI</span></footer></main>}
